"""Read AWAC wave data from processed ASCII files.

Reads wave data from Nortek AWAC processed wave files:
- .whd - Wave header data
- .wap - Processed wave parameters
- .was - Power spectra
- .wdr - Directional spectra  
- .wds - Full frequency-direction spectra

These files are generated by Nortek QuickWave or Storm software.

Mirrors MATLAB readAWACWaveAscii.m implementation.

Author: Kiro AI Assistant
Based on MATLAB implementation by Paul McCarthy, Guillaume Galibert
"""

from __future__ import annotations

from pathlib import Path
from typing import Any
import re

import numpy as np
import pandas as pd


def read_awac_wave_ascii(filename: Path | str) -> dict[str, Any] | None:
    """Read AWAC wave data from processed ASCII files.
    
    Reads wave header (.whd), processed wave data (.wap), power spectra (.was),
    directional spectra (.wdr), and full spectra (.wds) files generated by
    Nortek QuickWave or Storm software.
    
    Mirrors MATLAB readAWACWaveAscii.m function.
    
    Args:
        filename: Path to raw AWAC binary file (.wpr). Wave ASCII files are
                 located in the same directory with matching basename.
                 
    Returns:
        Dictionary with wave data, or None if files are missing.
        
    Dictionary keys:
        Time: MATLAB datenum timestamps
        Battery: Battery voltage (V)
        Heading: Magnetic heading (degrees)
        Pitch: Pitch angle (degrees)
        Roll: Roll angle (degrees)
        MinPressure: Minimum pressure (dbar)
        MaxPressure: Maximum pressure (dbar)
        Temperature: Temperature (°C)
        SignificantHeight: Significant wave height Hm0 (m)
        PeakPeriod: Peak period Tp (s)
        MeanZeroCrossingPeriod: Mean zero-crossing period Tz (s)
        PeakDirection: Peak direction (degrees)
        DirectionalSpread: Directional spread (degrees)
        MeanDirection: Mean direction (degrees)
        UnidirectivityIndex: Unidirectivity index
        MeanPressure: Mean pressure (dbar)
        pwrFrequency: Frequency vector for power spectra (Hz)
        dirFrequency: Frequency vector for directional spectra (Hz)
        pwrSpectrum: Power spectra (m²/Hz), shape (time, frequency)
        dirSpectrum: Directional spectra (degrees), shape (time, frequency)
        Direction: Direction vector (degrees)
        fullSpectrum: Full spectra (normalized energy/deg), shape (time, frequency, direction)
        isMagBias: True if magnetic correction applied
        magDec: Magnetic declination/compass offset (degrees)
        magBiasComment: Description of magnetic correction
        summary: Contents of .hdr file (list of strings)
        waveSummary: Contents of .whr file (list of strings)
        
    Additional keys if .wap has 31 columns:
        SpectraType: Spectrum type (0=Pressure, 1=Velocity, 3=AST)
        MeanOneThirdHeight: Mean 1/3 height H3 (m)
        MeanOneTenthHeight: Mean 1/10 height H10 (m)
        MaximumHeight: Maximum height Hmax (m)
        MeanHeight: Mean height Hmean (m)
        MeanPeriod: Mean period Tm02 (s)
        MeanOneThirdPeriod: Mean 1/3 period T3 (s)
        MeanOneTenthPeriod: Mean 1/10 period T10 (s)
        MaximumPeriod: Maximum period Tmax (s)
    """
    filename = Path(filename)
    
    # Get file paths
    file_path = filename.parent
    file_rad_name = filename.stem
    
    # Wave data files (generated by Nortek software)
    summary_file = file_path / f"{file_rad_name}.hdr"
    header_file = file_path / f"{file_rad_name}.whd"
    wave_summary_file = file_path / f"{file_rad_name}.whr"
    wave_file = file_path / f"{file_rad_name}.wap"
    dir_freq_file = file_path / f"{file_rad_name}.wdr"
    pwr_freq_file = file_path / f"{file_rad_name}.was"
    pwr_freq_dir_file = file_path / f"{file_rad_name}.wds"
    
    # Check if required files exist
    required_files = [
        summary_file, header_file, wave_summary_file,
        wave_file, dir_freq_file, pwr_freq_file, pwr_freq_dir_file
    ]
    
    missing_files = [f for f in required_files if not f.exists()]
    
    if missing_files:
        print("Missing wave data files:")
        for f in missing_files:
            print(f"  - {f.name}")
        print(f"\nInfo: To read wave data for {file_rad_name},")
        print("      .whd, .whr, .wap, .wdr, .was, .wds are required")
        print("      (use Nortek QuickWave or Storm software)")
        return None
    
    try:
        wave_data: dict[str, Any] = {}
        
        # Read summary files (text)
        if summary_file.exists():
            with open(summary_file, 'r') as f:
                wave_data['summary'] = f.readlines()
        
        if wave_summary_file.exists():
            with open(wave_summary_file, 'r') as f:
                wave_data['waveSummary'] = f.readlines()
        
        # Read data files (whitespace-delimited)
        header = np.loadtxt(header_file)
        wave = np.loadtxt(wave_file)
        dir_freq = np.loadtxt(dir_freq_file)
        pwr_freq = np.loadtxt(pwr_freq_file)
        pwr_freq_dir = np.loadtxt(pwr_freq_dir_file)
        
        # Extract compass offset from wave summary
        directional_offset = 0.0
        compass_offset = 0.0
        
        if 'waveSummary' in wave_data:
            # Find directional offset
            for line in wave_data['waveSummary']:
                match = re.search(r'(?i:Directional\s+Offset\s+)([\d\.\-]+)(?i:\s+deg\s*)', line)
                if match:
                    directional_offset = float(match.group(1))
                    break
            
            # Find compass offset
            for line in wave_data['waveSummary']:
                match = re.search(r'(?i:Compass\s+offset\s+)([\d\.\-]+)(?i:\s+deg\s*)', line)
                if match:
                    compass_offset = float(match.group(1))
                    break
        
        # Check offsets match
        if directional_offset != compass_offset:
            raise ValueError(
                f"Different directional offset ({directional_offset}) "
                f"and compass offset ({compass_offset})"
            )
        
        wave_data['isMagBias'] = False
        wave_data['magDec'] = directional_offset
        if wave_data['magDec'] != 0:
            wave_data['isMagBias'] = True
            wave_data['magBiasComment'] = (
                f"A compass correction of {wave_data['magDec']} degrees has been "
                f"applied to the data during wave processing stage "
                f"(usually to account for magnetic declination)."
            )
        else:
            wave_data['magBiasComment'] = ""
        
        # Replace missing value (-9.00) with NaN
        wave[wave == -9.00] = np.nan
        dir_freq[dir_freq == -9.00] = np.nan
        pwr_freq[pwr_freq == -9.000000] = np.nan
        pwr_freq_dir[pwr_freq_dir == -9.000000] = np.nan
        
        # Convert timestamps to MATLAB datenum
        header_time = _datetime_to_matlab_datenum(
            header[:, 2], header[:, 0], header[:, 1],
            header[:, 3], header[:, 4], header[:, 5]
        )
        
        wave_time = _datetime_to_matlab_datenum(
            wave[:, 2], wave[:, 0], wave[:, 1],
            wave[:, 3], wave[:, 4], wave[:, 5]
        )
        
        # Combine unique times
        total_time = np.unique(np.concatenate([header_time, wave_time]))
        i_header = np.isin(total_time, header_time)
        i_wave = np.isin(total_time, wave_time)
        
        n_time = len(total_time)
        wave_data['Time'] = total_time
        
        # Initialize arrays for header data
        wave_data['Battery'] = np.full(n_time, np.nan)
        wave_data['Heading'] = np.full(n_time, np.nan)
        wave_data['Pitch'] = np.full(n_time, np.nan)
        wave_data['Roll'] = np.full(n_time, np.nan)
        wave_data['MinPressure'] = np.full(n_time, np.nan)
        wave_data['MaxPressure'] = np.full(n_time, np.nan)
        wave_data['Temperature'] = np.full(n_time, np.nan)
        
        # Fill header data (columns 9-16, 0-indexed)
        wave_data['Battery'][i_header] = header[:, 9]
        wave_data['Heading'][i_header] = header[:, 11]
        wave_data['Pitch'][i_header] = header[:, 12]
        wave_data['Roll'][i_header] = header[:, 13]
        wave_data['MinPressure'][i_header] = header[:, 14]
        wave_data['MaxPressure'][i_header] = header[:, 15]
        wave_data['Temperature'][i_header] = header[:, 16]
        
        # Initialize arrays for wave data
        wave_data['SignificantHeight'] = np.full(n_time, np.nan)
        wave_data['PeakPeriod'] = np.full(n_time, np.nan)
        wave_data['MeanZeroCrossingPeriod'] = np.full(n_time, np.nan)
        wave_data['PeakDirection'] = np.full(n_time, np.nan)
        wave_data['DirectionalSpread'] = np.full(n_time, np.nan)
        wave_data['MeanDirection'] = np.full(n_time, np.nan)
        wave_data['UnidirectivityIndex'] = np.full(n_time, np.nan)
        wave_data['MeanPressure'] = np.full(n_time, np.nan)
        
        # Check format of wave data (31 columns = extended, 15 columns = simple)
        if wave.shape[1] == 31:
            # Extended format with all parameters
            wave_data['SpectraType'] = np.full(n_time, 9, dtype=np.uint8)
            wave_data['MeanOneThirdHeight'] = np.full(n_time, np.nan)
            wave_data['MeanOneTenthHeight'] = np.full(n_time, np.nan)
            wave_data['MaximumHeight'] = np.full(n_time, np.nan)
            wave_data['MeanHeight'] = np.full(n_time, np.nan)
            wave_data['MeanPeriod'] = np.full(n_time, np.nan)
            wave_data['MeanOneThirdPeriod'] = np.full(n_time, np.nan)
            wave_data['MeanOneTenthPeriod'] = np.full(n_time, np.nan)
            wave_data['MaximumPeriod'] = np.full(n_time, np.nan)
            
            # Fill extended wave data (columns 6-22, 0-indexed)
            wave_data['SpectraType'][i_wave] = wave[:, 6].astype(np.uint8)
            wave_data['SignificantHeight'][i_wave] = wave[:, 7]
            wave_data['MeanOneThirdHeight'][i_wave] = wave[:, 8]
            wave_data['MeanOneTenthHeight'][i_wave] = wave[:, 9]
            wave_data['MaximumHeight'][i_wave] = wave[:, 10]
            wave_data['MeanHeight'][i_wave] = wave[:, 11]
            wave_data['MeanPeriod'][i_wave] = wave[:, 12]
            wave_data['PeakPeriod'][i_wave] = wave[:, 13]
            wave_data['MeanZeroCrossingPeriod'][i_wave] = wave[:, 14]
            wave_data['MeanOneThirdPeriod'][i_wave] = wave[:, 15]
            wave_data['MeanOneTenthPeriod'][i_wave] = wave[:, 16]
            wave_data['MaximumPeriod'][i_wave] = wave[:, 17]
            wave_data['PeakDirection'][i_wave] = wave[:, 18]
            wave_data['DirectionalSpread'][i_wave] = wave[:, 19]
            wave_data['MeanDirection'][i_wave] = wave[:, 20]
            wave_data['UnidirectivityIndex'][i_wave] = wave[:, 21]
            wave_data['MeanPressure'][i_wave] = wave[:, 22]
        else:
            # Simple format (15 columns)
            wave_data['SignificantHeight'][i_wave] = wave[:, 6]
            wave_data['MeanZeroCrossingPeriod'][i_wave] = wave[:, 7]
            wave_data['PeakPeriod'][i_wave] = wave[:, 8]
            wave_data['PeakDirection'][i_wave] = wave[:, 9]
            wave_data['DirectionalSpread'][i_wave] = wave[:, 10]
            wave_data['MeanDirection'][i_wave] = wave[:, 11]
            wave_data['MeanPressure'][i_wave] = wave[:, 12]
            wave_data['UnidirectivityIndex'][i_wave] = wave[:, 13]
        
        # Extract frequency vectors
        wave_data['pwrFrequency'] = pwr_freq[0, :]
        wave_data['dirFrequency'] = dir_freq[0, :]
        
        n_pwr_freq = len(wave_data['pwrFrequency'])
        n_dir_freq = len(wave_data['dirFrequency'])
        
        # Initialize spectra arrays
        wave_data['dirSpectrum'] = np.full((n_time, n_dir_freq), np.nan)
        wave_data['pwrSpectrum'] = np.full((n_time, n_pwr_freq), np.nan)
        
        # Fill spectra data (skip first row which is frequency vector)
        wave_data['dirSpectrum'][i_wave, :] = dir_freq[1:, :]
        wave_data['pwrSpectrum'][i_wave, :] = pwr_freq[1:, :]
        
        # Extract direction vector
        wave_data['Direction'] = pwr_freq_dir[0, :]
        n_dir = len(wave_data['Direction'])
        
        # Initialize full spectrum array (time, frequency, direction)
        wave_data['fullSpectrum'] = np.full((n_time, n_dir_freq, n_dir), np.nan)
        
        # Calculate expected number of time samples in full spectrum
        n_time_full_spectrum = (pwr_freq_dir.shape[0] - 1) // n_dir_freq
        
        if n_time_full_spectrum != n_time:
            print(f"Info: Full directional spectrum in {file_rad_name}.wds")
            print(f"      is missing {n_time - n_time_full_spectrum} time samples.")
            print(f"      Assumed these were the last time samples.")
        
        # Reshape full spectrum: (freq*time, dir) -> (time, freq, dir)
        pwr_freq_dir_data = pwr_freq_dir[1:, :]  # Skip first row (direction vector)
        n_row, n_column = pwr_freq_dir_data.shape
        
        # Reshape to (time, frequency, direction)
        reshaped = pwr_freq_dir_data.reshape((n_time_full_spectrum, n_dir_freq, n_column))
        wave_data['fullSpectrum'][:n_time_full_spectrum, :, :] = reshaped
        
        return wave_data
        
    except Exception as e:
        print(f"Warning: Wave data for {file_rad_name} could not be read successfully.")
        print(f"Error: {str(e)}")
        return None


def _datetime_to_matlab_datenum(
    year: np.ndarray,
    month: np.ndarray,
    day: np.ndarray,
    hour: np.ndarray,
    minute: np.ndarray,
    second: np.ndarray
) -> np.ndarray:
    """Convert date/time components to MATLAB datenum.
    
    MATLAB datenum is days since 0000-01-01 00:00:00.
    
    Args:
        year: Year values
        month: Month values (1-12)
        day: Day values (1-31)
        hour: Hour values (0-23)
        minute: Minute values (0-59)
        second: Second values (0-59)
        
    Returns:
        MATLAB datenum values
    """
    from datetime import datetime
    
    result = np.zeros(len(year))
    
    for i in range(len(year)):
        try:
            dt = datetime(
                int(year[i]), int(month[i]), int(day[i]),
                int(hour[i]), int(minute[i]), int(second[i])
            )
            # Convert to MATLAB datenum
            ordinal = dt.toordinal()
            frac = (dt - datetime(dt.year, dt.month, dt.day)).total_seconds() / 86400.0
            result[i] = ordinal + 366 + frac  # MATLAB epoch offset
        except (ValueError, OverflowError):
            result[i] = np.nan
    
    return result
